### ISSUE TITLE
Separate markdown files for each category

### ISSUE THREAD

**Issue by UsmanAhmadSaeed** [PhantasticUniverse/CollectiveGenius-AutoGPT-Agent-Hub#1]
Hello,
The current readme is too long and I get tired of scrolling that much.
Please break down each section into it's separate markdown files.
Thank you very much!

**Comment by PhantasticUniverse** [comment]
Thanks for the suggestion. All done.

**Comment by UsmanAhmadSaeed** [comment]
> Thanks for the suggestion. All done.

![Pay up](https://media.tenor.com/Tk9YGYPs3JoAAAAd/we-take-credit-debit-or-paypal-pay-me.gif)
